version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - /data/mysql:/var/lib/mysql
    restart: always
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wsxdcf99%
      MYSQL_DATABASE: flaskapi
      MYSQL_USER: flaskapi
      MYSQL_PASSWORD: flaskapi
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - /data/mongodb:/data/db
    restart: always
    ports:
     - "27017:27017"
    environment:
       MONGODB_USERNAME: flaskapi
       MONGODB_PASSWORD: flaskapi
       MONGODB_DBNAME: flaskapi
